# Generated by Django 4.0.8 on 2023-11-17 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='lag',
            new_name='lon',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='open',
            new_name='operating_time',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='page_number',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='pincode',
            new_name='pin_code',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='pageno',
            new_name='store_name',
        ),
    ]
