# Generated by Django 4.0.8 on 2023-11-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0002_rename_lag_service_lon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='brand_logo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
