# Generated by Django 4.0.8 on 2023-11-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0003_alter_service_brand_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='store_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
