# Generated by Django 4.0.8 on 2023-11-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0004_alter_service_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='mobile',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
