# Generated by Django 4.0.8 on 2023-11-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0005_alter_service_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
