# Generated by Django 4.0.8 on 2023-11-27 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0006_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
