# Generated by Django 4.0.8 on 2023-11-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0007_alter_client_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius', models.FloatField()),
            ],
        ),
    ]
