# Generated by Django 4.0.8 on 2023-11-29 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0008_geofence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Geofence',
        ),
    ]
