# Generated by Django 4.0.8 on 2023-11-29 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0009_delete_geofence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='username',
        ),
    ]
