# Generated by Django 4.0.8 on 2023-11-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0011_supermarket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electronic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('store_name', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=600, null=True)),
                ('mobile', models.CharField(max_length=300, null=True)),
                ('operating_time', models.CharField(max_length=400, null=True)),
                ('lat', models.CharField(max_length=30, null=True)),
                ('lon', models.CharField(max_length=30, null=True)),
                ('pin_code', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('brand_logo', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
