# Generated by Django 4.0.8 on 2023-11-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0012_electronic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movietheater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('pin_code', models.CharField(max_length=15)),
                ('lat', models.CharField(max_length=30)),
                ('lon', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
    ]
