# Generated by Django 4.0.8 on 2023-11-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0014_telecom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telecom',
            name='operating_time',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='telecom',
            name='store_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
