# Generated by Django 4.0.8 on 2023-11-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0015_alter_telecom_operating_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telecom',
            name='address',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='telecom',
            name='brand_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='telecom',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='telecom',
            name='operating_time',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='telecom',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='telecom',
            name='store_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='telecom',
            name='store_type',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
