# Generated by Django 4.0.8 on 2023-11-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0016_alter_telecom_address_alter_telecom_brand_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealership_name', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('brand_name', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('lat', models.CharField(max_length=30, null=True)),
                ('lon', models.CharField(max_length=30, null=True)),
                ('pincode', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
