# Generated by Django 4.0.8 on 2023-12-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0018_remove_client_name_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
