# Generated by Django 4.0.8 on 2023-12-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0019_alter_client_email_alter_client_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
